### PR TITLE
Fix changeset get for nested properties with changes

### LINKED ISSUE #398: Multiple properties in nested key loses data on changeset.set
Weird behavior when a model has more than one property inside of a nested key. It seems that the data is lost in the changeset for a moment. 

In the example, we have the following model: 

```js
  model = {
    email: 'hi@gmail.com',
    user: {
      firstName: null,
      lastName: null
    },
    notifications: {
      email: true,
      sms: true
    }
  }
```

It's probably easier to see the issue in the gifs below.

## Version
3.0.0-beta.7

## Test Case
https://github.com/josemarluedke/--changeset-glimmer (Commit: https://github.com/josemarluedke/--changeset-glimmer/commit/10b7be96ea362378c0926b08cb504e705a1c4316)

## Steps to reproduce
Close repo, run app, change "user.firstName", change "user.lastName", Sumit form, change "user.firstName" again. You will see "user.lastName" will lose it's data.
See gifs below:

### Case 1, changing one checkbox, makes the second checkbox lose its data. 
Screen Recording 2020-01-10 at 09 45 PM

### Case 2, changing the value of input after the data is saved in the model makes the other input to lose its data.
Screen Recording 2020-01-10 at 09 44 PM

## Expected Behavior

Both properties in the same nested key should have its data intact.

@snewcomer Sorry for these issues, it's hard to explain some of them. Let me know if you have any questions.

### PR DESCRIPTION
**Pull request by josemarluedke**
This attempts to fix the issue in #398 and adds a test that covers the problem identified in the issue.

Closes #398.

### CODE REVIEW

**Comment by josemarluedke** [comment]
@snewcomer This PR is ready for review. 

Unfortunately, I had to add a workaround Ember Data Objects. I hope this PR makes sense. If you have a better approach to solve this issue, let me know.

File: addon/-private/validated-changeset.ts [hunk 1]
```diff
@@ -49,6 +49,12 @@ const AFTER_VALIDATION_EVENT = 'afterValidation';
 const AFTER_ROLLBACK_EVENT = 'afterRollback';
 const defaultValidatorFn = () => true;
 const defaultOptions = { skipValidate: false };
+const isEmberDataObject = (obj: Object) => {
```
Comment (snewcomer) [inline addon/-private/validated-changeset.ts]: what do you think about this take to check if an ember-data model? #406

Comment (josemarluedke) [reply addon/-private/validated-changeset.ts]: I believe it doesn't do the same thing. I could be wrong, just testing out to see if all tests pass.

File: addon/-private/validated-changeset.ts [hunk 2]
```diff
@@ -851,14 +857,27 @@ export class BufferedChangeset implements IChangeset {
...
+        result = normalizeObject(result);
+         let content: Content = this[CONTENT];
+
+        if (isObject(content[baseKey]) && !isEmberDataObject(content[baseKey])) {
+          let data: { [key: string]: any } = {}
+          Object.keys(content[baseKey]).forEach(k => {
+            data[k] = this.getDeep(content, `${baseKey}.${k}`)
+          })
+          return Object.assign(data, result);
+        }
```
Comment (snewcomer) [inline addon/-private/validated-changeset.ts]: Do we need this because Ember is asking for `user` and not the leaf key?  I was under the assumption that the key passed was the full path (but perhaps was pre Octane)...For example I see  the`key` arg as `cid` but never `user.name` for example.  Just `user` as the argument to `get`.

Overall this is great!  Can we add a comment on what we are trying to do?  What I gather is you are taking the `CHANGES` and merging with the `CONTENT` at that level in the object, correct?

Comment (josemarluedke) [reply addon/-private/validated-changeset.ts]: Yeah, I thought it did request the full path as well, but it doesn't. If I render `user.name`, the requested key is just `user`. 

We need this "merge" because the `user ` has changed, but only one property in it, causing the return value to be incomplete when having more than one property. 

The change here fetches the actual content and merge the changes on top of it, having complete data for a nested property.

I will add some comments to the code.

Comment (snewcomer) [reply addon/-private/validated-changeset.ts]: Screen Shot 2020-01-15 at 12 53 52 PM

Yeah looks like it traverses to the parent to find the value :( . Perhaps was a recent update, perhaps not.  

In any case, the fix you have here seems like the correct one.

File: addon/-private/validated-changeset.ts [hunk 3]
```diff
@@ -851,14 +857,32 @@ export class BufferedChangeset implements IChangeset {
       }
 
       if (result && isObject(result)) {
-        return normalizeObject(result);
-      }
+        result = normalizeObject(result);
+         let content: Content = this[CONTENT];
```
Comment (snewcomer) [inline addon/-private/validated-changeset.ts]: minor spacing issues when you have a chance (should be caught by a linter and is fixed in the `validated-changeset` repo)

File: addon/-private/validated-changeset.ts [hunk 4]
```diff
@@ -851,14 +857,32 @@ export class BufferedChangeset implements IChangeset {
...
+
+        // Merge the content with the changes to have a complete object for a nested property.
+        // Given a object with nested property and multiple properties inside of it, if the 
+        // requested key is the top most nested property and we have changes in of the properties, we need to 
+        // merge the original model data with the changes to have the complete object.
+        // eg. model = { user: { name: 'not changed', email: 'changed@prop.com'} }
+        if (isObject(content[baseKey]) && !isEmberDataObject(content[baseKey])) {
+          let data: { [key: string]: any } = {}
```
Comment (snewcomer) [inline addon/-private/validated-changeset.ts]: `let data: Record<string, any> = {}`

is another option

File: addon/-private/validated-changeset.ts (hunk 1 above)
Comment (snewcomer) [reply addon/-private/validated-changeset.ts]: Did you see if that worked?  We had another issue on EmberData objects and the fix on #406 seemed to fix it for them...

File: addon/-private/validated-changeset.ts (hunk 4 above)
Comment (josemarluedke) [reply addon/-private/validated-changeset.ts]: Changed.

File: addon/-private/validated-changeset.ts (hunk 3 above)
Comment (josemarluedke) [reply addon/-private/validated-changeset.ts]: Yeah, I had to disable all prettier and formatting in my editor to be able to work in these files, otherwise, my changes would be a lot of formatting. 

Anyway, I pushed a fix for the spacing.

File: addon/-private/validated-changeset.ts [hunk 5]
```diff
@@ -851,14 +857,32 @@ export class BufferedChangeset implements IChangeset {
...
+        if (isObject(content[baseKey]) && !isEmberDataObject(content[baseKey])) {
+          let data: Record<string, any> = {}
+          Object.keys(content[baseKey]).forEach(k => {
+            data[k] = this.getDeep(content, `${baseKey}.${k}`)
+          })
+          return Object.assign(data, result);
+        }
+
+          return result
+        }
```
Comment (snewcomer) [inline addon/-private/validated-changeset.ts]: These last two lines as well....

File: addon/-private/validated-changeset.ts (hunk 1 above)
Comment (snewcomer) [reply addon/-private/validated-changeset.ts]: Also noting that either way is fine with me.  Whatever seems more canonical is what we should do across the repo.

Comment (josemarluedke) [reply addon/-private/validated-changeset.ts]: @snewcomer I just tried a similar approach and it didn't work. If there isn't any other way to see if an object is and Ember Data object, then I think this change is fine.

Comment (snewcomer) [reply addon/-private/validated-changeset.ts]: Ok.  I don't want to drag this PR on as you seem to have fixed quite a good bug that surely will help others!

Ultimately, we would want a `util` to determine if something is an Ember Data object.  If #406 isn't it, we probably need to make sure we have the canonical way of doing so.

@luketheobscure
